name: Pull Request Comment

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post a comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: "Thank you for your PR! The team will review it soon 🚀."
            });
